import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Rose Rose ',
      slug: 'rose-rose',
      category: 'fleur',
      image: '/images/rose rose.png',
      price: 2.5,
      brand: 'Rose',
      rating: 4.5,
      numReviews: 59,
      countInStock: 25,
      description: ' cette rose est très populaire auprès des amoureux',
    },
    {
      name: 'Rose Blanche ',
      slug: 'rose-blanche',
      category: 'fleur',
      image: '/images/rose blanche.png',
      price: 2.8,
      brand: 'Rose',
      rating: 4,
      numReviews: 34,
      countInStock: 10,
      description: ' cette rose est très populaire auprès des ami(e)s',
    },
    {
      name: 'Rose Rouge ',
      slug: 'rose-rouge',
      category: 'fleur',
      image: '/images/rose rouge.png',
      price: 3.0,
      brand: 'Rose',
      rating: 5,
      numReviews: 200,
      countInStock: 150,
      description: ' cette rose est très populaire',
    },
    {
      name: 'Lilas ',
      slug: 'lilas-violet',
      category: 'fleur',
      image: '/images/lilas.png',
      price: 2.0,
      brand: 'Lilas',
      rating: 4.1,
      numReviews: 26,
      countInStock: 100,
      description: ' cette fleur Lilas est très populaire',
    },
    {
      name: 'Jasmin Blanche ',
      slug: 'jasmin',
      category: 'plante',
      image: '/images/jasmin.png',
      price: 25.8,
      brand: 'Jasmin',
      rating: 5,
      numReviews: 87,
      countInStock: 167,
      description: ' cette fleur jasmin est beaucoup achéter par les indiens',
    },
    {
      name: 'Lavande',
      slug: 'lavande',
      category: 'fleur',
      image: '/images/lavande.png',
      price: 2.8,
      brand: 'Lavande',
      rating: 5.5,
      numReviews: 99,
      countInStock: 400,
      description: ' cette fleur est très populaire',
    },
    {
      name: 'Jacinthe Rose',
      slug: 'jacinthe',
      category: 'plante',
      image: '/images/jacinthe.png',
      price: 40,
      brand: 'Jacinthe',
      rating: 4.1,
      numReviews: 20,
      countInStock: 100,
      description: 'Populaire',
    },
    {
      name: 'Hortensia Bleue',
      slug: 'Hortensia',
      category: 'fleur',
      image: '/images/hortensia.png',
      price: 2.9,
      brand: 'hortensia',
      rating: 3.8,
      numReviews: 57,
      countInStock: 150,
      description: 'Très populaire',
    },
    {
      name: 'Hortensia Rouge',
      slug: 'Hortensia-Rouge',
      category: 'fleur',
      image: '/images/hortensia rouge.png',
      price: 2.9,
      brand: 'hortensia',
      rating: 3.8,
      numReviews: 57,
      countInStock: 150,
      description: 'Très populaire',
    },
    {
      name: 'Hortensia Viollette',
      slug: 'Hortensia-Viollette',
      category: 'fleur-artificiel',
      image: '/images/hortensia viollette.png',
      price: 4.13,
      brand: 'hortensia',
      rating: 4.8,
      numReviews: 77,
      countInStock: 200,
      description: 'Très populaire',
    },
    {
      name: 'Amaryllis',
      slug: 'Amaryllis',
      category: 'plante',
      image: '/images/Amaryllis.png',
      price: 36,
      brand: 'Amaryllis',
      rating: 2.45,
      numReviews: 30,
      countInStock: 130,
      description: 'Très jolie',
    },
    {
      name: 'Astrantia',
      slug: 'Astrantia',
      category: 'plante',
      image: '/images/astrantia.png',
      price: 42,
      brand: 'Astrantia',
      rating: 3.8,
      numReviews: 25,
      countInStock: 80,
      description: 'Très jolie et cela sans très bon',
    },
    {
      name: 'Dahlia',
      slug: 'Dahlia',
      category: 'fleur',
      image: '/images/dahlia.png',
      price: 4,
      brand: 'Dahlia',
      rating: 2.9,
      numReviews: 67,
      countInStock: 50,
      description: 'Très jolie',
    },
    {
      name: 'Myosotis',
      slug: 'Myosotis',
      category: 'plante',
      image: '/images/myosotis.png',
      price: 50,
      brand: 'Myosotis',
      rating: 2.3,
      numReviews: 80,
      countInStock: 100,
      description: 'Très jolie',
    },
    {
      name: 'Crocosmia',
      slug: 'Crocosmia',
      category: 'fleur',
      image: '/images/crocosmia.png',
      price: 4.53,
      brand: 'Crocosmia',
      rating: 1.3,
      numReviews: 40,
      countInStock: 70,
      description: 'Belle couleur',
    },
    {
      name: 'Fressia',
      slug: 'Fressia',
      category: 'fleur',
      image: '/images/fressia.png',
      price: 6,
      brand: 'Fressia',
      rating: 3.3,
      numReviews: 50,
      countInStock: 60,
      description: 'plusieurs couleurs est très populaire',
    },
    {
      name: 'Fressia Blanche',
      slug: 'Fressia blanche',
      category: 'fleur',
      image: '/images/fressia blanche.png',
      price: 3,
      brand: 'Fressia Blanche',
      rating: 4.3,
      numReviews: 80,
      countInStock: 120,
      description: 'Très populaire',
    },
    {
      name: 'Glaïeul',
      slug: 'Glaïeul',
      category: 'fleur',
      image: '/images/Glaïeul.png',
      price: 9,
      brand: 'Glaïeul',
      rating: 6.3,
      numReviews: 90,
      countInStock: 200,
      description: 'Très populaire pour les bouquets de fleurs',
    },
    {
      name: 'Muscari',
      slug: 'Muscari',
      category: 'plante',
      image: '/images/muscari.png',
      price: 28,
      brand: 'Muscari',
      rating: 4.3,
      numReviews: 70,
      countInStock: 130,
      description: 'Très populaire',
    },
    {
      name: 'Lisianthus',
      slug: 'Lisianthus',
      category: 'fleur',
      image: '/images/lisianthus.png',
      price: 3.5,
      brand: 'Lisianthus',
      rating: 5.3,
      numReviews: 89,
      countInStock: 140,
      description: 'Très populaire',
    },
  ],
};

export default data;
