import Head from 'next/head';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Zona</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/zona.png" />
      </Head>

      <h1 className="text-3xl font-bold">Zona</h1>
    </div>
  );
}
